development:
  scheme: http
  host: localhost
  port: 4000
  database:
    sql:
      host: localhost
      port: 5432
      name: chatr_development
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
    mongo:
      scheme: mongodb
      host: localhost
      port: 27017
      name: chatrAPI
      secret: secret